### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by billimek** [trojanc/node-influx-uptimerobot#4]
Hey FYI I adopted this into a [helm chart](https://github.com/billimek/billimek-charts/tree/master/uptimerobot).  It's from a fork because I wanted to add a delay between runs so the container can be long-lived.  If interested, I can PR the delay changes into this repo.

**Comment by trojanc** [comment]
Hi, great stuff! Sure PR is welcome. I still need to look at your previous issue (#3)... I haven't been paying attention to this project for a while...

**Comment by trojanc** [comment]
I see what you mean... it exists immediately. I originally intended it to be run from a cron-like service. But now that it become a docker thing too, it makes more sense to keep the process alive. I'll add a update for that. I'm busy reworking some code too to make it easier to work with docker

**Comment by billimek** [comment]
Awesome, these changes are great - thank you!  Updated helm chart to adapt.
